\c songs_dev;

INSERT INTO songs (name, artist, album, time, is_favorite) VALUES
('Dark Fantasy', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '4:40', true),
('Gorgeous', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '5:57', true),
('POWER', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '4:52', true),
('All Of The Lights', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '4:59', true),
('Monster', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '6:18', true),
('So Appalled', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '6:37', true),
('Devil In A New Dress', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '5:51', true),
('Runaway', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '9:07', true),
('Hell Of A life', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '5:27', true),
('Blame Game', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '7:49', true),
('Lost In the World', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '4:16', true),
('Who Will Survive In America', 'Kanye West', 'My Beautiful Dark Twisted Fantasy', '1:38', true),
('State Of Grace', 'Taylor Swift', 'Red', '4:55', false),
('Red', 'Taylor Swift', 'Red', '3:40', false),
('Treacherous', 'Taylor Swift', 'Red', '4:00', false),
('I Knew You Were Trouble.', 'Taylor Swift', 'Red', '3:37', false),
('All Too Well', 'Taylor Swift', 'Red', '5:27', false),
('22', 'Taylor Swift', 'Red', '3:50', false),
('I Almost Do', 'Taylor Swift', 'Red', '4:02', false),
('We Are Never Ever Getting Back Together', 'Taylor Swift', 'Red', '3:11', false),
('Stay Stay Stay', 'Taylor Swift', 'Red', '3:24', false),
('The Last Time', 'Taylor Swift', 'Red', '4:58', false),
('Holy Ground', 'Taylor Swift', 'Red', '3:21', false),
('Sad Beautiful Tragic', 'Taylor Swift', 'Red', '4:43', false),
('The Lucky One', 'Taylor Swift', 'Red', '4:00', false),
('Everything Has Changed', 'Taylor Swift', 'Red', '4:03', false),
('Starlight', 'Taylor Swift', 'Red', '3:37', false),
('Begin Again', 'Taylor Swift', 'Red', '3:57', false),
('IGORS THEME', 'Tyler, The Creator', 'IGOR', '3:20', false),
('EARFQUAKE', 'Tyler, The Creator', 'IGOR', '3:10', true),
('I THINK', 'Tyler, The Creator', 'IGOR', '3:32', false),
('EXACTLY WHAT YOU RUN FROM YOU END UP CHASING', 'Tyler, The Creator', 'IGOR', '0:14', false),
('RUNNING OUT OF TIME', 'Tyler, The Creator', 'IGOR', '2:57', false),
('NEW MAGIC WAND', 'Tyler, The Creator', 'IGOR', '3:15', true),
('A BOY IS A GUN*', 'Tyler, The Creator', 'IGOR', '3:30', false),
('PUPPET', 'Tyler, The Creator', 'IGOR', '2:59', false),
('WHATS GOOD', 'Tyler, The Creator', 'IGOR', '3:25', false),
('GONE, GONE / THANK YOU', 'Tyler, The Creator', 'IGOR', '6:15', true),
('I DONT LOVE YOU ANYMORE', 'Tyler, The Creator', 'IGOR', '2:41', false),
('ARE WE STILL FRIENDS', 'Tyler, The Creator', 'IGOR', '4:25', true);

INSERT INTO albums ( name, artist) VALUES
( 'My Beautiful Dark Twisted Fantasy', 'Kanye West' ),
( 'Red', 'Taylor Swift' ),
( 'IGOR', 'Tyler, The Creator' )